---
- apt: update_cache=yes

- name: install the package, force upgrade
  apt:
    force_apt_get: yes
    name: ['unzip', 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']
    install_recommends: yes

- name: Install Ansible via Pip.
  pip:
    name: ['awscli' ,'ansible']

- name: Generate /.ssh/id_rsa RSA host key
  command: ssh-keygen -q -t rsa -f .ssh/id_rsa -C "" -N ""

- name: Key permission
  file: path=".ssh/{{ item }}" mode=0655
  with_items:
    - id_rsa
    - id_rsa.pub


