---

- file: name={{ deploy_app_dir }} state=directory  mode=0755

- name: Moving Application YML
  template:
    src: files/docker-compose.yml.j2
    dest: "{{ deploy_app_dir }}/docker-compose.yml.j2"

- name: Moving deploy script
  template:
    src: files/start_service.sh.j2
    dest: "{{ deploy_app_dir }}/start_service.sh"

- name: Execute the script
  command: sh {{ deploy_app_dir }}/start_service.sh
