---
- name: NGINX | Adding NGINX signing key
  apt_key: url=http://nginx.org/keys/nginx_signing.key state=present

- name: NGINX | Adding sources.list deb url for NGINX
  lineinfile: dest=/etc/apt/sources.list line="deb http://nginx.org/packages/mainline/ubuntu/ bionic nginx"

- name: NGINX Plus | Adding sources.list deb-src url for NGINX
  lineinfile: dest=/etc/apt/sources.list line="deb-src http://nginx.org/packages/mainline/ubuntu/ bionic nginx"

- name: NGINX | Updating apt cache
  apt:
    update_cache: yes

- name: Installing Nginx
  apt: name=nginx state=latest
  become: yes

- name: start nginx
  service:
    name: nginx
    state: started
  become: yes

- name: Template a file to nginx
  template:
    src: files/nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: restart nginx
  service:
    name: nginx
    state: restarted
  become: yes
